:q exiting, fixed <l> key movement, init update

diff --git a/init b/init
--- a/init
+++ b/init
@@ -62,7 +62,6 @@ install_packages() {
 	shift
 	local packages=("$@")
 
-	echo -e "${INFO} ${BLUE}Installing missing packages: ${packages[*]}${RESET}"
 	case "$distro" in 
 		debian)
 			sudo apt-get update
@@ -97,9 +96,13 @@ else
 	echo -e "${GREEN}[CREATED] Project bin directory created.${RESET}"
 fi
 
-required_packages=("ncurses" "make")
+required_packages=("ncurses" "make") # arch
 if [ "$distro" == "debian" ]; then
 	required_packages=("libncursesw5-dev" "make")
+elif [ "$distro" == "rpm" ]; then
+	required_packages=("ncurses", "make")
+elif [ "$distro" == "fedora" ]; then
+	required_packages=("ncurses", "make")
 fi
 missing_packages=()
 for package in "${required_packages[@]}"; do
@@ -112,7 +115,22 @@ for package in "${required_packages[@]}"; do
 done
 
 if [ ${#missing_packages[@]} -ne 0 ]; then
-	install_packages "$distro" "${missing_packages[@]}"
+	echo -e "${INFO} There are some missing packages. Would you like to install them (y/N): " 
+	read ans
+	case $ans in
+		[yY])
+			echo -e "${INFO} ${BLUE}Installing missing packages: ${packages[*]}${RESET}"
+			install_packages "$distro" "${missing_packages[@]}"
+			;;
+
+		[nN])
+			echo -e "${INFO} Could not proceed installation. Aborting..."
+			exit 1
+			;;
+		*)
+			echo -e "ddd"
+			;;
+	esac
 else
 	echo -e "${INFO} ${GREEN}${BOLD}All required_packages are already installed${RESET}"
 fi
@@ -124,7 +142,7 @@ echo -e "${GREEN}[CREATED] Project is made${RESET}"
 attempts=0
 max_attempts=3
 while ((attempts < max_attempts)); do
-	read -p "Do you want to add croco to your /bin/ folder (y/N): " ans
+	read -p "Do you want to add croco to your /bin/ folder (afterwards you  will be asked about creating alias) (y/N): " ans
 	case $ans in
 		[yY])
 			sudo cp "$bin_dir/$app_name" /usr/bin/
@@ -143,7 +161,32 @@ while ((attempts < max_attempts)); do
 	((++attempts))
 done
 
-if (( attempts == max_attempts )); then
+if ((attempts == max_attempts)); then
+	echo -e "${RED}[ERROR]${RESET} ${RED}${BOLD}Wrong inputs: 3. Aborting...${RESET}"
+	exit 1
+fi
+
+attempts=0
+while ((attempts < max_attempts)); do
+	read -p "Do you want to create alias for croco app (y/N): " ans
+	case $ans in
+		[yY])
+			echo "Created alias"
+			break
+			;;
+
+		[nN])
+			break
+			;;
+
+		*)
+			echo -e "${RED}[ERROR]${RESET} ${RED}Invalid input. Please try again${RESET}"
+			;;
+	esac
+	((++attempts))
+done
+
+if ((attempts == max_attempts)); then
 	echo -e "${RED}[ERROR]${RESET} ${RED}${BOLD}Wrong inputs: 3. Aborting...${RESET}"
 	exit 1
 fi
